### ISSUE TITLE
BACKUP_TARGET unused

### ISSUE THREAD

**Issue by rbrv** [workingconcept/forge-backup#1]
I love the simplicity and elegancy of your script! Thanks for sharing!

2 notes while going over it while implementing: 

- It seems like [`BACKUP_TARGET="/home/forge"`](https://github.com/workingconcept/forge-backup/blob/5cf755ef9a5b0eeee1a8ed47a88537a3012a7d05/restic-setup.sh#L45) is unused. Later in the script, [`/home/forge`](https://github.com/workingconcept/forge-backup/blob/5cf755ef9a5b0eeee1a8ed47a88537a3012a7d05/restic-setup.sh#L204) is hardcoded.
- As your script is backing up the whole contents of `/home/forge`, isn't `/home/forge/backup` backupped as well? Creating some sort of nested backup?

**Comment by mattstein** [comment]
Thanks for the feedback!

That’s rather embarrassing about not using `BACKUP_TARGET`. I’ll fix it and see if I can test with a Ploi server. (Managing fewer servers now and haven’t been on Forge for a while.)

Backing up all of `/home/forge`, including its nested backup folder, was on purpose though. The idea was to take the home folder and the database dumps in one (admittedly lazy) go. Could just as well restore a database dump locally as keep copies of everything in an offsite archive. I made sure those local backups get pruned so things don’t get out of hand.

**Comment by mattstein** [comment]
I spiffed up a few little things on this branch, if you’d care giving it a try: https://github.com/workingconcept/forge-backup/tree/fix-backup-target

If you’ve already set this up somewhere, you could update it in place instead:

1. Edit `/root/restic/conf/b2.conf` to add a line with `BACKUP_TARGET="/home/forge"` or whatever you’d prefer.
2. Edit `/root/restic/restic-backup.sh` to [replace `/home/forge` with `$BACKUP_TARGET`](https://github.com/workingconcept/forge-backup/commit/8a4f25d5bd52329245eb66f83952c8826a51e647#diff-f077d3695a30ff1736e113515bc73ab9b0a771187b5e9de4b1029dc1ccdea77cR209).
3. Optionally edit `/root/restic/mysql-backup.sh` to include [that `--no-tablespaces` option](https://github.com/workingconcept/forge-backup/commit/8a4f25d5bd52329245eb66f83952c8826a51e647#diff-f077d3695a30ff1736e113515bc73ab9b0a771187b5e9de4b1029dc1ccdea77cR173) and [exclude `performance_schema|mysql|sys`](https://github.com/workingconcept/forge-backup/commit/8a4f25d5bd52329245eb66f83952c8826a51e647#diff-f077d3695a30ff1736e113515bc73ab9b0a771187b5e9de4b1029dc1ccdea77cR164) from the table listing.

Setup, database backups, restic backups, and restic mounting all worked fine on a Ploi server and with a new B2 bucket—just switched that new `SERVICE` var to `"ploi"`.

**Comment by rbrv** [comment]
Thanks for the clarification! Really helpful!

> Backing up all of /home/forge, including its nested backup folder, was on purpose though.

I actually really like this approach, keeps things simple!
